config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  resources :books, only: [:new, :index, :show, :edit, :destroy]
    patch 'books/:id' => 'books#update', as: 'update_book'
  resources :users, only: [:show, :index, :edit, :update]
  get 'home/about', as: 'about'
  post 'books' => 'books#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'books/index'
    end
  end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(current_user.id)
    @book_id = Book.find(params[:id])
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render 'books/edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book_id = Book.find(params[:id])
    @user = @book_id.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.profile_image.attach(params[:avatar]) if @user.profile_image.blank?
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render 'users/edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
  <% if @book.errors.any? %>
  <div class="error">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/books/_info.html.erb
<h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100), class: 'attachment user profile_image fallback' %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "/users/#{user.id}/edit", class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="me-3">New book</h2>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 pc-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
      <%= render 'books/error' %>
        <div  class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :Opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-em-0">
  <%= render 'books/error' %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
            <tbody>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80,80), class: 'attachment user profile_image fallback' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tbody>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/info', user: @book_id.user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <td>
            <%= link_to user_path(@book_id.user.id) do %>
              <%= image_tag @book_id.user.get_profile_image(80,80), class: 'attachment user profile_image fallback' %><br>
              <%= @book_id.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book_id.id) do %>
              <%= @book_id.title %>
            <% end %>
          </td>
          <td>
            <%= @book_id.body %>
          </td>
          <td>
            <% if @book_id.user == current_user %>
              <%= link_to "Edit", "/books/#{@book_id.id}/edit", class: 'btn btn-sm btn-success edit_book_33' %>
            <% end %>
          </td>
          <td>
            <% if @book_id.user == current_user %>
              <%= link_to "Destroy", book_path(@book_id), method: :delete, "data-confirm" => "本当に消しますか?", class: 'btn btn-sm btn-danger' %>
            <% end %>
          </td>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
                  <i class="fas fa-sign-out-alt text-light"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
        </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <% if @user.errors.any? %>
          <div class="error">
            <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-em-0">
  <%= render 'books/error' %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>naem</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <td>
              <%= image_tag user.get_profile_image(100,100), class: 'attachment user profile_image fallback' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-em-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
            <tbody>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag @user.get_profile_image(40,40), class: 'attachment user profile_image fallback' %><br>
                  <%= book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tbody>
          <% end %>
      </table>
    </div>
  </div>
</div>